import scrapy
import time
import random

class MetacriticSpider(scrapy.Spider):
    name = "metacritic"

    artists = [
      "Jack",
      "Frank Ocean",
      "B.o.B",
      "Swizz Beatz",
      "Kent Jones",
      "Roscoe Dash",
      "Mack Wilds",
      "Carnage",
      "Puff Daddy",
      "Rocko",
      "Ace Hood",
      "Eminem",
      "I LOVE MAKONNEN",
      "Macklemore",
      "Problem",
      "Kevin \"Chocolate Droppa\" Hart",
      "Justin Timberlake",
      "YelaWolf",
      "Rich Homie Quan",
      "Janet",
      "Aminé",
      "Bryson Tiller",
      "Pusha T",
      "Belly",
      "CJ Hilton",
      "Verse Simmonds",
      "Keri Hilson",
      "Busta Rhymes",
      "Wiz Khalifa",
      "Tamia",
      "Machine Gun Kelly",
      "Maxwell",
      "Teyana Taylor",
      "Avant",
      "Russ",
      "R. Kelly",
      "Snakehips",
      "A Boogie Wit da Hoodie",
      "Young Thug",
      "Zayion McCall",
      "Wale",
      "Young Dro",
      "MGK",
      "Tyler, The Creator",
      "Raekwon",
      "Diggy",
      "Rich Gang",
      "Charlie Wilson",
      "Tyga",
      "Ro James",
      "Monica",
      "P Reign",
      "Jhene Aiko",
      "iHeartMemphis",
      "Mindless Behavior",
      "Bruno Mars",
      "2 Chainz",
      "Usher",
      "Ne-Yo",
      "Damien",
      "Kevin Gates",
      "Future",
      "Waka Flocka Flame",
      "Ledisi",
      "Zendaya",
      "Maejor Ali",
      "Keyshia Cole",
      "Sean Kingston",
      "Eric Benet",
      "Mario",
      "Amine",
      "Aloe Blacc",
      "PnB Rock",
      "Bobby Shmurda",
      "Melanie Fiona",
      "Jay-Z",
      "Lloyd",
      "Driicky Graham",
      "Kanye West",
      "Pharrell",
      "NAV",
      "Lil Durk",
      "Fabolous",
      "Lupe Fiasco",
      "Toni Braxton",
      "Rob $tone",
      "Dae Dae",
      "New Boyz",
      "O.T. Genasis",
      "Machine Gun Kelly,Young Thug",
      "Kelly Price",
      "Jasmine V",
      "Brandy",
      "Tamar Braxton",
      "Joe Budden",
      "Cameron Dallas",
      "Kendrick Lamar",
      "DLOW",
      "Aretha Franklin",
      "A$AP Ferg",
      "SWV",
      "Nicki Minaj",
      "Jennifer Hudson",
      "Miguel",
      "Kirko Bangz",
      "T-Wayne",
      "Kid Ink",
      "John Legend",
      "Elle Varner",
      "Bobby V",
      "Bando Jonez",
      "DJ Luke Nasty",
      "Trinidad James",
      "DMX",
      "Koryn Hawthorne",
      "DJ Drama",
      "Natalie La Rose",
      "Mike Will Made-It",
      "The-Dream",
      "@iHeartMemphis",
      "Missy Elliott",
      "J. Dash",
      "Michael Jackson",
      "T.I.",
      "Lil Yachty",
      "August Alsina",
      "Nicholas David",
      "Juicy J",
      "Clyde Carson",
      "Bandit Gang Marco",
      "Anthony David",
      "YC",
      "A Tribe Called Quest",
      "Nelly",
      "Marvin Sapp",
      "Kehlani",
      "Snoop Dogg",
      "Solange",
      "E-40",
      "2Virgins",
      "SoMo",
      "Wham!",
      "Post Malone",
      "Yo Gotti",
      "QUE.",
      "Young M.A",
      "Chief Keef",
      "Justin Bieber",
      "Ciara",
      "Ayo",
      "Meek Mill",
      "Zay Hilfigerrr",
      "Big Sean",
      "Tee Grizzley",
      "Nicki Minaj,Hustle Gang",
      "DJ Khaled",
      "Omarion",
      "YFN Lucci",
      "Chedda Da Connect",
      "Chance The Rapper",
      "Colonel Loud",
      "Calvin Harris",
      "Robin Thicke",
      "Sage The Gemini",
      "Lil Dicky",
      "Ray J",
      "Drop City Yacht Club",
      "Big K.R.I.T.",
      "Dr. Dre",
      "Ty Dolla $ign",
      "Pharrell Williams",
      "Anthony Hamilton",
      "Estelle",
      "Common",
      "Beyonce",
      "Jeremih",
      "Nebu Kiniza",
      "Trevin Hunte",
      "LoveRance",
      "Mali Music",
      "DeJ Loaf",
      "Tinashe",
      "Hopsin",
      "Flo Rida",
      "The FiNATTiCZ",
      "Plies",
      "Birdman",
      "Khalid",
      "Que",
      "Lil Uzi Vert",
      "6LACK",
      "Mykko Montana",
      "Alicia Keys",
      "Eazy-E",
      "OB OBrien",
      "Mariah Carey",
      "Dwele",
      "Alessia Cara",
      "Fat Joe",
      "George Tandy",
      "Ugly God",
      "Kid Cudi",
      "Mike WiLL Made-It,Young Greatness",
      "Jonn Hart",
      "Tech N9Ne",
      "MadeinTYO",
      "Andra Day",
      "21 Savage",
      "Hoodie Allen",
      "XXXTENTACION",
      "50 Cent",
      "K Camp",
      "Young Money",
      "Joey Bada$$",
      "2 Milly",
      "Chris Brown",
      "Mary Mary",
      "Janelle Monae",
      "Tech N9ne",
      "Action Bronson",
      "Young Jeezy",
      "Red Cafe",
      "Jason Derulo",
      "QUE",
      "KYLE",
      "Mac Miller",
      "Cee Lo Green",
      "French Montana",
      "Missy \"Misdemeanor\" Elliott",
      "B. Smyth",
      "Tank",
      "Curren$Y",
      "Jill Scott",
      "Mike Will Made It",
      "Desiigner",
      "Jidenna",
      "Urban Mystic",
      "Keith Sweat",
      "YG,J. Cole",
      "Tameka Tiny Harris",
      "Chris Jamison",
      "Fetty Wap",
      "Young M.a.",
      "Kirk Franklin",
      "TeeFLii",
      "Ghost Town DJ's",
      "Travis Porter",
      "Rae Sremmurd",
      "Travi$ Scott",
      "Tory Lanez",
      "Ludacris",
      "Earl Sweatshirt",
      "Silento",
      "Kat Dahlia",
      "Trey Songz",
      "Bei Maejor",
      "Lil' Boosie",
      "Whitney Houston",
      "T-Pain",
      "Tessanne Chin",
      "Ca$h Out",
      "G-Eazy",
      "Kem",
      "will.i.am",
      "iLoveMemphis",
      "Johnny Gill",
      "Kelly Rowland",
      "Travis Scott",
      "We Are Toonz",
      "Game",
      "N.W.A",
      "Musiq Soulchild",
      "Marsha Ambrosius",
      "K. Michelle",
      "A$AP Rocky",
      "KCamp",
      "D.R.A.M.",
      "Rico Love",
      "Shy Glizzy",
      "Drake",
      "Childish Gambino",
      "Tamela Mann",
      "Mike WiLL Made-It",
      "DJ Mustard",
      "Gucci Mane",
      "Tyrese",
      "Ca$hOut",
      "Mary J. Blige",
      "Tink",
      "Rick Ross",
      "Jamie Foxx",
      "Tinie Tempah",
      "Prince",
      "Sevyn Streeter",
      "Anita Baker",
      "Iggy Azalea",
      "Jay Z",
      "Rob Stone",
      "The Weeknd",
      "Candice Glover",
      "DJ Suede The Remix God",
      "Logic",
      "Dreezy",
      "John Heart",
      "Lil Wayne",
      "Luke Nasty",
      "YG",
      "Rihanna",
      "Snootie Wild",
      "ScHoolboy Q",
      "Emeli Sande",
      "Kodak Black",
      "Jeezy",
      "OG Maco",
      "DJ ESCO",
      "Fantasia",
      "The Game",
      "Migos",
      "PARTYNEXTDOOR",
      "Major Lazer",
      "Empire Cast",
      "D'Angelo",
      "M-City J.R.",
      "Adrian Marcel"
    ]

    start_urls = [
        "http://www.metacritic.com/browse/albums/genre/date/rb",
        "http://www.metacritic.com/browse/albums/genre/date/rap",
    ]

    def parse(self, response):
        album_selectors = response.css('li.product.release_product')

        for selector in album_selectors:
            url = selector.css('a::attr(href)').extract_first()
            album = selector.css('a::text').extract_first().strip()
            score = selector.css('div.metascore_w::text').extract_first()
            artist = selector.css('li.stat.product_artist > span.data::text').extract_first()
            yield {
                'url': url,
                'album': album,
                'score': score,
                'artist': artist,
            }

        time.sleep(random.random())
        
        next_url = response.css('#main > div.module.filter.genre_filter > div.page_nav > div > div.page_flipper > span.flipper.next > a::attr(href)').extract_first()
        yield scrapy.Request(url=response.urljoin(next_url), callback=self.parse)
